name: Build and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DOCKER_IMAGE: jobet9530/animalcare
  DOCKER_TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/animalcare
      DOCKER_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Notify success
        if: success()
        run: echo "Docker image ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} built and pushed successfully!"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the new image
            docker pull ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

            # Stop and remove existing container
            docker stop animalcare || true
            docker rm animalcare || true

            # Run new container
            docker run -d \
              --name animalcare \
              -p 9002:9002 \
              --env-file .env \
              ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
